export const queryKeys = {
  session: ["session"] as const,
  users: (params?: unknown) => ["users", params] as const,
  user: (id: number) => ["users", id] as const,
  customers: (params?: unknown) => ["customers", params] as const,
  customer: (id: number) => ["customers", id] as const,
  devices: (params?: unknown) => ["devices", params] as const,
  device: (id: number) => ["devices", id] as const,
  deviceCatalogs: ["device-catalogs"] as const,
  tickets: (params?: unknown) => ["repair-tickets", params] as const,
  ticket: (id: number) => ["repair-tickets", id] as const,
  ticketHistory: (id: number) => ["repair-tickets", id, "status-history"] as const,
  ticketAttachments: (id: number) => ["repair-tickets", id, "attachments"] as const,
  diagnoses: (ticketId: number) => ["repair-tickets", ticketId, "diagnoses"] as const,
  quotations: (ticketId: number) => ["repair-tickets", ticketId, "quotations"] as const,
  quotation: (id: number) => ["quotations", id] as const,
  parts: (params?: unknown) => ["parts", params] as const,
  part: (id: number) => ["parts", id] as const,
  partTransactions: (id: number, params?: unknown) => ["parts", id, "transactions", params] as const,
  partRequests: (params?: unknown) => ["part-requests", params] as const,
  partRequest: (id: number) => ["part-requests", id] as const,
  repairLogs: (ticketId: number) => ["repair-tickets", ticketId, "repair-logs"] as const,
  testResults: (ticketId: number) => ["repair-tickets", ticketId, "test-results"] as const,
  ticketTimeline: (ticketId: number) => ["repair-tickets", ticketId, "timeline"] as const,
  invoices: (params?: unknown) => ["invoices", params] as const,
  invoicePreview: (ticketId: number) => ["repair-tickets", ticketId, "invoice-preview"] as const,
  invoice: (id: number) => ["invoices", id] as const,
  invoicePayments: (id: number) => ["invoices", id, "payments"] as const,
  refundApprovers: ["payments", "refund-approvers"] as const,
  notifications: (params?: unknown) => ["notifications", params] as const,
  unreadNotifications: ["notifications", "unread-count"] as const,
  delivery: (ticketId: number) => ["repair-tickets", ticketId, "delivery"] as const,
  review: (ticketId: number) => ["repair-tickets", ticketId, "review"] as const,
  reports: (name: string, params?: unknown) => ["reports", name, params] as const,
  assignableTechnicians: ["repair-tickets", "assignable-technicians"] as const,
};
