export const TICKET_STATUSES = [
  "NEW",
  "RECEIVED",
  "ASSIGNED",
  "DIAGNOSING",
  "WAITING_FOR_QUOTATION",
  "WAITING_FOR_CUSTOMER_APPROVAL",
  "CUSTOMER_REJECTED",
  "WAITING_FOR_PARTS",
  "REPAIRING",
  "TESTING",
  "COMPLETED",
  "READY_FOR_DELIVERY",
  "DELIVERED",
  "CLOSED",
  "ON_HOLD",
  "CANCELLED",
] as const;

export type TicketStatus = (typeof TICKET_STATUSES)[number];

export const ALLOWED_TICKET_TRANSITIONS: Readonly<
  Record<TicketStatus, readonly TicketStatus[]>
> = {
  NEW: ["RECEIVED", "CANCELLED"],
  RECEIVED: ["ASSIGNED", "ON_HOLD", "CANCELLED"],
  ASSIGNED: ["DIAGNOSING", "ON_HOLD"],
  DIAGNOSING: ["WAITING_FOR_QUOTATION", "ON_HOLD"],
  WAITING_FOR_QUOTATION: ["WAITING_FOR_CUSTOMER_APPROVAL", "DIAGNOSING"],
  WAITING_FOR_CUSTOMER_APPROVAL: [
    "WAITING_FOR_QUOTATION",
    "WAITING_FOR_PARTS",
    "REPAIRING",
    "CUSTOMER_REJECTED",
    "CANCELLED",
  ],
  CUSTOMER_REJECTED: ["READY_FOR_DELIVERY", "CLOSED"],
  WAITING_FOR_PARTS: [
    "WAITING_FOR_CUSTOMER_APPROVAL",
    "REPAIRING",
    "ON_HOLD",
    "CANCELLED",
  ],
  REPAIRING: ["TESTING", "WAITING_FOR_PARTS", "ON_HOLD"],
  TESTING: ["COMPLETED", "REPAIRING"],
  COMPLETED: ["READY_FOR_DELIVERY"],
  READY_FOR_DELIVERY: ["COMPLETED", "DELIVERED"],
  DELIVERED: ["CLOSED"],
  CLOSED: [],
  ON_HOLD: ["RECEIVED", "ASSIGNED", "DIAGNOSING", "WAITING_FOR_PARTS", "REPAIRING"],
  CANCELLED: [],
};
